name: ${COMPOSE_PROJECT_NAME:-telemetry-intake-service}

x-base: &base
  build:
    context: ..
    dockerfile: ./docker/Dockerfile
  restart: unless-stopped
  env_file:
    - ../.env
  networks:
    - iot-hub-nw

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iot-hub-nw

  telemetry-intake-mqtt-adapter:
    <<: *base
    image: telemetry-intake-mqtt-adapter
    container_name: telemetry-intake-mqtt-adapter
    command: [ "python", "-m", "mqtt_adapter.main" ]
    depends_on:
      mosquitto:
        condition: service_healthy

  telemetry-intake-http:
    <<: *base
    image: telemetry-intake-http
    container_name: telemetry-intake-http
    ports:
      - ${HTTP_PORT:-8000}:${HTTP_PORT:-8000}
    command: [ "uvicorn", "api.main:app",  "--host", "0.0.0.0", "--port", "${HTTP_PORT:-8000}" ]

volumes: { }

networks:
  iot-hub-nw:
    external: true
